name: Fix Markdown Newlines in All MD Files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run fix script
        run: python markdown_newline_fixer.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "fix: add two spaces at line ends for markdown newlines"
          file_pattern: '*/*.md'
          skip_dirty_check: false
